### ISSUE TITLE
Cannot Find Module 'express;

### ISSUE THREAD

**Issue by trismegistis** [ming08108/EtherPool#2]
C:\Users\ryan\Desktop\ether>node run.js
module.js:340
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\ryan\Desktop\ether\run.js:3:15)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)

**Comment by ming08108** [comment]
Did you run npm install?

**Comment by trismegistis** [comment]
Yeah its having a lot of trouble probably because I'm on windows. It can't
find vc resist even though it's installed and on the path

**Comment by ming08108** [comment]
I have no experience using node on windows. I would suggest using a Linux box because compiling some node modules on windows is hard and sometimes impossible.

**Comment by ming08108** [comment]
I am closing this issue.
