### ISSUE TITLE
runPayments.py Error

### ISSUE THREAD

**Issue by duclub** [ming08108/EtherPool#5]
Probably something stupid, as I don't know Python well.

```
~/EtherPool$ python runPython.py
Traceback (most recent call last):
  File "runPayments.py", line 46, in <module>
    txId = sendTx(myAddress, address, value)
  File "runPayments.py", line 16, in sendTx
    response = requests.post(url,headers=headers, json=message)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'
```

**Comment by ming08108** [comment]
You need to install a newer version of the requests library.
